// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_STATE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_STATE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STATE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STATE, -70);
    lv_obj_set_y(ui_STATE, -150);
    lv_obj_set_align(ui_STATE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STATE, "State:");
    lv_obj_set_style_text_font(ui_STATE, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TOOL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TOOL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TOOL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TOOL, -70);
    lv_obj_set_y(ui_TOOL, 0);
    lv_obj_set_align(ui_TOOL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TOOL, "Tool:");
    lv_obj_set_style_text_font(ui_TOOL, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BED = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BED, -70);
    lv_obj_set_y(ui_BED, 150);
    lv_obj_set_align(ui_BED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BED, "Bed:");
    lv_obj_set_style_text_font(ui_BED, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
